<div class="jumbotron">
    <h1><span class="zf-green">Edit simpleName id: <?= $simpleNameId ?></span></h1>
    <?php
        $simpleNameForm->setAttribute('action', $this->url('simpleName',
            [
            'action' => 'edit',
            'id' => $simpleNameId
            ]
        ));
        $simpleNameForm->prepare();
        echo $this->form()->openTag($simpleNameForm);
        
        echo $this->formRow($simpleNameForm->get('property1'));
        echo $this->formRow($simpleNameForm->get('property2'));

        
        echo $this->formSubmit($simpleNameForm->get('submit'));
        echo $this->form()->closeTag();
    ?>
</div>
