<div class="jumbotron">
    <h1><span class="zf-green">SimpleName</span></h1>
    <a href="<?= $this->url('simpleName', ['action' => 'add']) ?>">Add SimpleName</a>
    <table class="table">
        <tr>
        <th>Id</th>
        
        <th>Property1</th>
        <th>Property2</th>

        <th>Actions</th>
        
        </tr>
        <?php foreach ($simpleNameRows as $simpleName): ?>
        <tr>
            <td><?= $simpleName->getId() ?></td>
            
            <td><?= $simpleName->getProperty1() ?></td>
            <td><?= $simpleName->getProperty2() ?></td>

            <td>
                <a href="<?= $this->url('simpleName', ['action' => 'edit', 'id' => $simpleName->getId()]) ?>">Edit</a> |
                <a href="<?= $this->url('simpleName', ['action' => 'delete', 'id' => $simpleName->getId()]) ?>">Remove</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
    
    <?= $this->paginationControl(
        $simpleNameRows,
        'Sliding',
        'pagination',
        ['route' => 'simpleName/paginator']
    ) ?>
</div>
